FROM python:2.7.13
ADD requirements.txt /tmp/requirements.txt
RUN apt-get update && apt-get install -y libldap2-dev libsasl2-dev
RUN apt-get install -y vim
RUN pip install -r /tmp/requirements.txt
RUN adduser --uid 1085 --disabled-password --gecos '' ${user:-jvzantvoort}
ARG user
USER ${user:-jvzantvoort}
RUN git clone https://github.com/jvzantvoort/jvzantvoort-vim-config.git /home/${user:-jvzantvoort}/.vim \
    && mkdir -p ~/.vim/bundle \
    && git clone https://github.com/tomasr/molokai.git ~/.vim/bundle/molokai \
    && cd /home/${user:-jvzantvoort}/.vim \
    && ./bootstrap.sh
ADD . /code
WORKDIR /code
EXPOSE 5000
VOLUME /webroot
CMD ["/bin/bash"]
